version: "3.8"
services:

  prison-api:
    image: ghcr.io/ministryofjustice/prison-api:latest
    networks:
      - hmpps
    container_name: prison-api
    ports:
      - "8091:8091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/health"]
    environment:
      - SERVER_PORT=8091
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

networks:
  hmpps:
