version: "3"
services:
  prisoner-contact-registry:
    build:
      context: .
    network_mode: "host"
    container_name: prisoner-contact-registry
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: oauth
    ports:
      - "8090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

networks:
  hmpps:
